SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_RADIUS = 20
LINE_WIDTH = 2

PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 3
SHOT_EXPLOTION_START_SIZE = 1
SHOT_EXPLOTION_PROPIGATION_SPEED = 300
SHOT_EXPLOTION_MAX_SIZE = 3
PLAYER_SHOT_SPEED = 800
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

MISSILE_RADIUS = 5
MISSILE_EXPLOTION_START_SIZE = 5
MISSILE_EXPLOTION_PROPIGATION_SPEED = 100
MISSILE_EXPLOTION_MAX_SIZE = 100
MISSILE_SPEED = 200
MISSILE_COOLDOWN_SECONDS = 5